// Note:
// When adding new keymap name, do not forget adding it
// to KEYMAP_NAMES in webview/constants.ts also.
type KeymapName
    = 'next-tweet'
    | 'previous-tweet'
    | 'unfocus-tweet'
    | 'scroll-down-page'
    | 'scroll-up-page'
    | 'scroll-up-to-top'
    | 'scroll-down-to-bottom'
    | 'switch-home-timeline'
    | 'switch-notifications'
    | 'switch-direct-messages'
    | 'switch-default-url'
    | 'switch-search'
    | 'open-devtools'
    | 'new-tweet'
    | 'send-tweet'
    | 'reply-tweet'
    | 'retweet-tweet'
    | 'quote-tweet'
    | 'like-tweet'
    | 'open-images'
    | 'open-images-in-browser'
    | 'open-tweet'
    | 'open-links'
    | 'show-user'
    | 'browser-go-back'
    | 'browser-go-forward'
    | 'browser-reload'
    | 'zoom-in'
    | 'zoom-out'
    | 'quit-app'
;
