export const CLASS_NAMES = {
    tweet: '_1eF_MiFx',
    scrollUpToNewTweet: '_1olbCNTo',
    header: '_7kIt4uMb',
};

export const SELECTORS = {
    tweet: `div.${CLASS_NAMES.tweet}[role="row"]`,
    notificationCount: '.Fe7ul3Lt.Z_PqXzzk._2DggF3sL._2izplv41',
    scrollUpToNewTweet: `.${CLASS_NAMES.scrollUpToNewTweet}`,
    tabItems: `._2QuQvRFT._2ZoxDI7c`,
    newTweet: '._2tOLusnc._2ZBD52R7',
    cancelNewTweet: '.INAWBu0V._3PLvX7RF.Q1vpCyfl',
    sendTweet: '.MmJh82_T._1xFtK706.SpbPGaHr._2Rz0TobF._1pzUva68._2m0B23vv._3f2NsD-H',
    tweetAction: 'button.RQ5ECnGZ._1m0pnxeJ',
    selectionDialogItems: '.MmJh82_T.SpbPGaHr._3vxCixKF._2Rz0TobF._1pzUva68._1qpWiIkN._3f2NsD-H',
    thumbnailImageInTweet: 'a._2YXT0EI-',
    tweetBody: 'div.I8DvYjmD._2HNcekSk',
    tweetText: 'h1._3f2NsD-H',
    thumbnailLinkInTweet: 'div._3hdqTVua._3f2NsD-H a._3kGl_FG7',
    header: `header.${CLASS_NAMES.header}`,
    notifications: 'svg._20oY9XAa',
    tweetActions: 'div._1t1yuVSm._3_8jWiwP._32ievKrg._3f2NsD-H',
    notificationIndicator: 'span.Fe7ul3Lt.Z_PqXzzk._2DggF3sL._2izplv41',
};

export const KEYMAP_NAMES: KeymapName[] = [
    'next-tweet',
    'previous-tweet',
    'unfocus-tweet',
    'scroll-down-page',
    'scroll-up-page',
    'scroll-up-to-new-tweet',
    'switch-home-timeline',
    'switch-notifications',
    'switch-direct-messages',
    'switch-search',
    'new-tweet',
    'send-tweet',
    'reply-tweet',
    'retweet-tweet',
    'quote-tweet',
    'like-tweet',
    'open-images',
    'open-images-in-browser',
    'open-tweet',
    'open-links',
    'open-devtools',
    'browser-go-back',
    'browser-go-forward',
    'browser-reload',
    'quit-app',
];

export const TWITTER_COLOR = '#1da1f2';
